// <auto-generated />
namespace OnlineExamManagement.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tainermodelmodifiedforprocessingimg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tainermodelmodifiedforprocessingimg));
        
        string IMigrationMetadata.Id
        {
            get { return "201809272030095_tainer model modified for processing img"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
