// <auto-generated />
namespace OnlineExamManagement.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addalltabletothedatabaselazyloading : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addalltabletothedatabaselazyloading));
        
        string IMigrationMetadata.Id
        {
            get { return "201809251644329_add all table to the database,lazy loading"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
