// <auto-generated />
namespace OnlineExamManagement.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class course_trainer_organization_relation_indatabase_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(course_trainer_organization_relation_indatabase_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201809100717193_course_trainer_organization_relation_indatabase_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
